---
dist: xenial
language: python
python:
  - '3.8'
install:
  - pip install coveralls
  - make venv
script: make test
after_success:
  - coveralls
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
